services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network
  database:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network
  backend:
    image: e-commerce
    container_name: spring-boot-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      createDummyData: ${CREATE_DUMMY_DATA:-false}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - ecommerce-network

volumes:
  mysql-data:

networks:
  ecommerce-network: